data = struct('LMU_200',[],...
    'LMU_201',[],...
    'LMU_202',[],...
    'LMU_203',[],...
    'LMU_204',[],...
    'LMU_205',[],...
    'LMU_206',[],...
    'LMU_207',[],...
    'LMU_208',[],...
    'LMU_209',[],...
    'LMU_210',[],...
    'LMU_211',[],...
    'LMU_212',[],...
    'LMU_213',[],...
    'LMU_214',[],...
    'LMU_215',[],...
    'LMU_216',[],...
    'LMU_217',[],...
    'LMU_218',[],...
    'LMU_219',[],...
    'LMU_220',[],...
    'LMU_221',[],...
    'LMU_222',[]);

data_fields = fields(data);
s = 2;
for t = 1:numel(fields(data))
    
    l = 1;
    d = cell(1,1);
    split_res = regexp(data_fields{t},'_','split');
    while CH_ID(s,1) == str2double(split_res{2})
       d{l,1} = {DATE{s,1}, VALUE(s,1), VALID_SAMPLES(s,1)};
       l = l+1;
        
       s = s+1;
       if s > size(CH_ID,1)
           data.(data_fields{t}) = d;
           break;
       end
       if CH_ID(s,1) ~= str2double(split_res{2})
           data.(data_fields{t}) = d;
           break;
       end
    end
    data.(data_fields{t}) = d;
    for e = 1:size(data.(data_fields{t}),1)
        data.(data_fields{t}){e}(4) = {date2utc(datevec(cell2mat(data.(data_fields{t}){e}(1))))};
        if (cell2mat(data.(data_fields{t}){e}(2)) == 1000 || cell2mat(data.(data_fields{t}){e}(2)) == 999.9) && strcmp(data_fields{t},'LMU_220') ~= 1
            w1 = cell2mat(data.(data_fields{t}){e-1}(2));
            w2 = cell2mat(data.(data_fields{t}){e+1}(2));
            data.(data_fields{t}){e}(2) = {(w2-w1)/2+w1};
        end   
    end
    for e = 1:size(data.(data_fields{t}),1)
        utcdiff = cell2mat(data.(data_fields{t}){e+1}(4))-cell2mat(data.(data_fields{t}){e}(4));
        if utcdiff > 60
            part1 = {data.(data_fields{t}){1:e}}';
            part2 = {data.(data_fields{t}){(e+1):end}}';
            w3 = cell2mat(data.(data_fields{t}){e}(2));
            w4 = cell2mat(data.(data_fields{t}){e+2}(2));
            insertpart(2) = {(w4-w3)/2+w3};
            insertpart(4) = {cell2mat(data.(data_fields{t}){e}(4))+60};
            data.(data_fields{t}) = {part1{:} insertpart part2{:}}';            
        end
    end
    
    
end
clear part1 part2 l e split_res s insertpart data_fields w3 w4 utcdiff CH_ID DATE1 SINGLE_READING VALID_SAMPLES VALUE MAX MIN d SD
